//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public decimal Course_ID { get; set; }
        public decimal Faculty_ID { get; set; }
        public string Course_Code { get; set; }
        public string Course_Name { get; set; }
        public string Course_Description { get; set; }
        public decimal CreatedBy { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public decimal ModifiedBy { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public bool IsActive { get; set; }
    }
}
